version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      # Change "dev" to "prod" in production
      - APP_ENV=dev
      - APP_DEBUG=true
      - GH_TOKEN=putAValidGithubToken
      - GH_SECURED_TOKEN=putAValidSecuredToken
    volumes:
      # Comment out the next line in production
      - ./:/srv/prestonbot:rw
      # This is for assets:install
      - ./web:/srv/prestonbot/web:rw
      # If you develop on Linux, comment out the following volumes to just use bind-mounted project directory from host
      - /srv/prestonbot/var
      - /srv/prestonbot/var/cache
      - /srv/prestonbot/var/logs
      - /srv/prestonbot/var/sessions
      - /srv/prestonbot/vendor
    networks:
      - prestonbot
  nginx:
    image: nginx:1.11-alpine
    depends_on:
      - app
    ports:
      - '81:80'
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./web:/srv/prestonbot/web:ro
    networks:
      - prestonbot

volumes:
  app-web: {}

networks:
  prestonbot: ~
