name: PHP

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.1', '7.2', '7.3']
    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: xdebug

    - uses: actions/checkout@v2

    - name: Get composer cache directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install dependencies
      run: |
        composer install --no-interaction
        ./vendor/bin/simple-phpunit install

    - name: PHPUnit
      run: SYMFONY_DEPRECATIONS_HELPER=weak ./vendor/bin/simple-phpunit

    - name: PHPStan
      if: matrix.php-versions == '7.3'
      run: composer phpstan

    - name: Lint PHP
      run: ./vendor/bin/php-cs-fixer fix --config=.php_cs -v --dry-run

    - name: Lint TWIG
      run: ./bin/console lint:twig app/Resources

    - name: Lint YAML
      run: ./bin/console lint:yaml app/config

    - name: Security Check
      if: matrix.php-versions == '7.3'
      run: |
        curl -L https://github.com/fabpot/local-php-security-checker/releases/download/v1.0.0/local-php-security-checker_1.0.0_linux_386 -o ./security-checker
        chmod a+x ./security-checker
        ./security-checker --path=composer.lock

    - name: Upload coverage results to Coveralls
      if: matrix.php-versions == '7.3'
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.4.3/php-coveralls.phar
        chmod +x php-coveralls.phar
        php php-coveralls.phar --coverage_clover=build/clover.xml --json_path=build/coveralls-upload.json -vvv
